/****************************************************************************/
/*  MACRO for cufont.exe only 15 JAN 89                                     */
/*  Updated: Suttipong Kanakakorn
             Sun  08-06-1989  10:04:26                                      */
/****************************************************************************/
#define MAXCOL 256
#define HUNAKADMITO 0xdb  /* treat as upper level */
