/****************************************************************************/
/*  INC.H 15 JAN 89                                                         */
/****************************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dir.h>

#include "..\common\kbdcode.h"
#include "..\common\const.h"
#include "..\common\cwtype.h"
#include "..\common\proto.h"
#include "const.h"
#include "proto.h"
