#
# makefile for cw.exe
# Updated: Suttipong Kanakakorn
#          Sun  08-06-1989  16:25:44
#
# TCC_OPTION -w = enable all warning
#
TCC_OPTION=-w -DCW

\cw\cw.exe: \
        ..\common\edisp.obj ..\common\hdisp.obj ..\common\adisp.obj \
        ..\common\grdetect.obj \
        ..\common\cwgrphc.obj ..\common\cwegrph.obj ..\common\cwagrph.obj \
        ..\common\ekbd.obj \
        ..\common\cscrn.obj ..\common\fileutil.obj ..\common\dir.obj \
        ..\common\sound.obj ..\common\cusong.obj \
        scrn.obj getstr.obj tutil1.obj edit.obj ins.obj del.obj \
        menu.obj \
        kbd.obj status.obj move.obj movement.obj wrap.obj \
        onscrn.obj file.obj search.obj block.obj cw.obj cwsetup.obj \
        mainsyls.obj thaieng.obj worewaan.obj FINDCHAR.obj HOREHEEB.obj \
        HUNAKAD.obj JULCUT.obj KARAN.obj LEADCON.obj \
        MAIMALAI.obj MAIMUAN.obj NOPCUT.obj NSTRCMP.obj ROREREO.obj \
        RORERU.obj SARAA.obj SARAAH.obj SARAAIR.obj SARAIE.obj \
        SARAO.obj SARAR.obj SARAU.obj SARAUE.obj SARAUEE.obj \
        SARAUM.obj GLOBAL.obj
    tcc -c ..\common\stampdate.c
    tlink   @scuw.tlr

scrn.obj: scrn.c var.h
    tcc -c $(TCC_OPTION) scrn.c

getstr.obj: getstr.c var.h
    tcc -c  $(TCC_OPTION) getstr.c

tutil1.obj: tutil1.c var.h
    tcc -c  $(TCC_OPTION) tutil1.c

edit.obj: edit.c var.h
    tcc -c -v $(TCC_OPTION) edit.c

ins.obj: ins.c var.h
    tcc -c -v $(TCC_OPTION) ins.c

del.obj: del.c var.h
    tcc -c  $(TCC_OPTION) del.c

menu.obj: menu.c var.h ..\common\cwgrphc.h
    tcc -c $(TCC_OPTION) menu.c

kbd.obj: kbd.c var.h
    tcc -c $(TCC_OPTION) kbd.c

status.obj:  status.c var.h
    tcc -c  $(TCC_OPTION) status.c

move.obj: move.c var.h
    tcc -c  $(TCC_OPTION) move.c

movement.obj: movement.c var.h
    tcc -c $(TCC_OPTION) movement.c

wrap.obj: wrap.c var.h
    tcc -c $(TCC_OPTION) wrap.c

onscrn.obj: onscrn.c var.h
    tcc -c $(TCC_OPTION) onscrn.c

file.obj: file.c var.h
    tcc -c $(TCC_OPTION) file.c

search.obj: search.c var.h
    tcc -c $(TCC_OPTION) search.c

block.obj: block.c var.h
   tcc -c -v $(TCC_OPTION) block.c

cw.obj: cw.c var.h ..\common\cwgrphc.h
   tcc -c $(TCC_OPTION) cw.c

cwsetup.obj: cwsetup.c var.h
    tcc -c $(TCC_OPTION) cwsetup.c

#
# TUD KUM
#

MAINSYLS.OBJ: mainsyls.c
   tcc -c $(TCC_OPTION) mainsyls.c
THAIENG.OBJ: thaieng.c
   tcc -c THAIENG.c
WOREWAAN.OBJ: worewaan.c
   tcc -c worewaan.c
FINDCHAR.OBJ: findchar.c
   tcc -c findchar.c
HOREHEEB.OBJ: horeheeb.c
    tcc -c horeheeb.c
HUNAKAD.OBJ: hunakad.c
    tcc -c hunakad.c
JULCUT.OBJ: julcut.c
    tcc -c julcut.c
KARAN.OBJ: karan.c
    tcc -c karan.c
LEADCON.OBJ: leadcon.c
    tcc -c leadcon.c
MAIMALAI.OBJ: maimalai.c
    tcc -c maimalai.c
MAIMUAN.OBJ: maimuan.c
    tcc -c  maimuan.c
NOPCUT.OBJ: nopcut.c
    tcc -c nopcut.c
NSTRCMP.OBJ: nstrcmp.c
    tcc -c nstrcmp.c
ROREREO.OBJ: rorereo.c
    tcc -c rorereo.c
RORERU.OBJ: roreru.c
    tcc -c roreru.c
SARAA.OBJ: saraa.c
    tcc -c saraa.c
SARAAH.OBJ: saraah.c
    tcc -c saraah.c
SARAAIR.OBJ: saraair.c
    tcc -c saraair.c
SARAIE.OBJ: saraie.c
    tcc -c saraie.c
SARAO.OBJ: sarao.c
    tcc -c sarao.c
SARAR.OBJ: sarar.c
    tcc -c sarar.c
SARAU.OBJ: sarau.c
    tcc -c sarau.c
SARAUE.OBJ: saraue.c
    tcc -c saraue.c
SARAUEE.OBJ: sarauee.c
    tcc -c sarauee.c
SARAUM.OBJ: saraum.c
    tcc -c saraum.c
GLOBAL.OBJ: global.c
    tcc -c global.c
