/*
    Routine.h
*/

unsigned char *dummy();
unsigned char *SaraUmRtn();
unsigned char *SaraAhRtn();
unsigned char *SaraUeeRtn();
unsigned char *SaraArWithoutTnl();
unsigned char *MaiMalaiRtn();
unsigned char *MaiMalaiFC();
unsigned char *SaraAirRtn();
unsigned char *SaraORtn();
unsigned char *SaraRRtn();
unsigned char *LeadConRtn();
unsigned char *RoreReoRtn();
unsigned char *RoreRuRtn();
unsigned char *SaraARtn();
unsigned char *SaraAhRtn();
unsigned char *SaraUmRtn();
unsigned char *MaiTaiKuuRtn();
unsigned char *SaraUURtn();
unsigned char *SaraERtn();
unsigned char *OrAngRtn();
unsigned char *HunAkadRtn();
unsigned char *KaranRtn();
unsigned char *MaiMuanRtn();
unsigned char *SaraIeRtn();
unsigned char *SaraUeRtn();
unsigned char *SaraURtn();
unsigned char *WoreWaanRtn();
unsigned char *HorHeebRtn();
unsigned char *CntlChar();
unsigned char *PuncChar();
unsigned char *TermChar();
unsigned char *FCPuncChar();
unsigned char *PaiYarnnoyRtn();
unsigned char *MaiYamokRtn();

unsigned char *SaraRWithoutTnl();
unsigned char *SaraRWithMaiTri();
unsigned char *SaraRWithTonal();
unsigned char *SaraORtn();
unsigned char *SaraAirRtn();
unsigned char *MaiMalaiRtn();
unsigned char *MaiMalaiFC();
unsigned char *LeadConRtn();
