/*
	thai.h -- thai characters

	Copyright Subun & Tanat
	Used with permission, Sahaviriya System
	All rights reserved.
*/

#ifndef __THAI__
#define __THAI__

#define KoreGai		(unsigned char) 0xA1	/*	ก	*/
#define KorKai		(unsigned char) 0xA2	/*	ข	*/
#define KorKuad		(unsigned char) 0xA3	/*		*/
#define KoreKwai	(unsigned char) 0xA4	/*	ค	*/
#define KoreKon		(unsigned char) 0xA5	/*		*/
#define KoreRakung	(unsigned char) 0xA6	/*	ฆ	*/
#define NgorNgoo	(unsigned char) 0xA7	/*	ง	*/
#define JoreJarn	(unsigned char) 0xA8	/*	จ	*/
#define ChorChing	(unsigned char) 0xA9	/*	ฉ	*/
#define ShoreChang	(unsigned char) 0xAA	/*	ช	*/
#define SoreSoe		(unsigned char) 0xAB	/*	ซ	*/
#define ShoreKracher	(unsigned char) 0xAC	/*	ฌ	*/
#define YoreYing	(unsigned char) 0xAD	/*	ญ	*/
#define DoreChada	(unsigned char) 0xAE	/*	ฎ	*/
#define TorePatak	(unsigned char) 0xAF	/*	ฏ	*/
#define ThorSantan	(unsigned char) 0xB0	/*	ฐ	*/
#define ToreMontoe	(unsigned char) 0xB1	/*	ฑ	*/
#define TorePootao	(unsigned char) 0xB2	/*	ฒ	*/
#define NoreNane	(unsigned char) 0xB3	/*	ณ	*/
#define DoreDek		(unsigned char) 0xB4	/*	ด	*/
#define ToreTao		(unsigned char) 0xB5	/*	ต	*/
#define ThorToong	(unsigned char) 0xB6	/*	ถ	*/
#define ToreTaharn	(unsigned char) 0xB7	/*	ท	*/
#define ToreTong	(unsigned char) 0xB8	/*	ธ	*/
#define NoreNoo		(unsigned char) 0xB9	/*	น	*/
#define BoreBaimai	(unsigned char) 0xBA	/*	บ	*/
#define PorePla		(unsigned char) 0xBB	/*	ป	*/
#define PorPeng		(unsigned char) 0xBC	/*	ผ	*/
#define ForFa		(unsigned char) 0xBD	/*	ฝ	*/
#define PoreParn	(unsigned char) 0xBE	/*	พ	*/
#define ForeFun		(unsigned char) 0xBF	/*	ฟ	*/
#define PoreSumpao	(unsigned char) 0xC0	/*	ภ	*/
#define MoreMar		(unsigned char) 0xC1	/*	ม	*/
#define YoreYak		(unsigned char) 0xC2	/*	ย	*/
#define RoreReo		(unsigned char) 0xC3	/*	ร	*/
#define RoreRu		(unsigned char) 0xC4	/*	ฤ	*/
#define LoreLing	(unsigned char) 0xC5	/*	ล	*/
#define WoreWaan	(unsigned char) 0xC7	/*	ว	*/
#define SoreSala	(unsigned char) 0xC8	/*	ศ	*/
#define SoreRusi	(unsigned char) 0xC9	/*	ษ	*/
#define SoreSeo		(unsigned char) 0xCA	/*	ส	*/
#define HorHeeb		(unsigned char) 0xCB	/*	ห	*/
#define LorChula	(unsigned char) 0xCC	/*	ฬ	*/
#define OrAng		(unsigned char) 0xCD	/*	อ	*/
#define HorNokHook	(unsigned char) 0xCE	/*	ฮ	*/

#define PaiYarnnoy	(unsigned char) 0xCF	/*	ฯ	*/
#define	SaraAh		(unsigned char) 0xD0	/*	สระอะ	*/
#define	HunAkad		(unsigned char) 0xD1	/*	ไม้หันอากาศ	*/
#define	SaraR		(unsigned char) 0xD2	/*	สระอา	*/
#define	SaraUm		(unsigned char) 0xD3	/*	สระอำ	*/
#define	SaraIe		(unsigned char) 0xD4	/*	สระอิ	*/
#define	SaraE		(unsigned char) 0xD5	/*	สระอี	*/
#define	SaraUe		(unsigned char) 0xD6	/*	สระอึ	*/
#define	SaraUee		(unsigned char) 0xD7	/*	สระอือ	*/
#define	SaraU		(unsigned char) 0xD8	/*	สระอุ	*/
#define	SaraUU		(unsigned char) 0xD9	/*	สระอู	*/
#define 	ThaiDot		(unsigned char) 0xDA	/*		*/
#define	SaraA		(unsigned char) 0xE0	/*	สระเอ	*/
#define 	SaraAir		(unsigned char) 0xE1	/*	สระแอ	*/
#define 	SaraO			(unsigned char) 0xE2	/*	สระโอ	*/
#define	MaiMuan		(unsigned char) 0xE3	/*	ไม้ม้วน	*/
#define	MaiMalai		(unsigned char) 0xE4	/*	ไม้มลาย	*/
#define 	MaiYamok		(unsigned char) 0xE6  /* ไม้ยมก */
#define	MaiTaiKuu	(unsigned char) 0xE7	/*	ไม้ไต่คู้	*/
#define	MaiEk		(unsigned char) 0xE8	/*	ไม้เอก	*/
#define	MaiToe		(unsigned char) 0xE9	/*	ไม้โท	*/
#define	MaiTri		(unsigned char) 0xEA	/*	ไม้ตรี	*/
#define	MaiJattawa	(unsigned char) 0xEB	/*	ไม้จัตวา	*/
#define	Karan		(unsigned char) 0xEC	/*	การันต์	*/

#define	_Exclamation	(unsigned char) 0x21	/* ! */
#define	_Dollar		(unsigned char) 0x24	/* $ */
#define	_Percent		(unsigned char) 0x25	/* % */
#define	_OpenParen	(unsigned char) 0x28	/* วงเล็บเปิด*/
#define	_CloseParen	(unsigned char) 0x29	/* วงเล็บปิด */
#define	_Hyphen		(unsignec char) 0x2D	/* - */
#define	_FullStop	(unsigned char) 0x2E	/* . */

#define	_Colon		(unsigned char) 0x3A
#define	_SemiColon	(unsigned char) 0x3B
#define	_Question	(unsigned char) 0x3F	/* ? */
#define 	_LeftBracket	(unsigned char) 0x5B	/* [ */
#define	_RightBracket (unsigned char) 0x5D	/* ] */
#define	_LeftBrace	(unsigned char) 0x7B	/* { */
#define	_RightBrace	(unsigned char) 0x7D	/* } */
#define	_Baht		(unsigned char) 0xDF	/* ฿	*/

# endif __THAI__
