/* ---------- Thai Character code for Printer ----------- */
/* Suttipong Kanakakorn Sat  10-28-1989  10:41:46 , receive BALI at 0xDA,ed,ee */
#include    "cpthai.h"

/* ----- SMO Character ----- */
char	cp_thaitable[] = {
	CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,
	CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,
	CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,
	CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,
	CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,
	CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,
	CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,
	CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,
	CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,
	CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,
	CP_MIDDLE ,CP_UPPER  ,CP_MIDDLE ,CP_MIDDLE ,CP_UPPER  ,CP_UPPER	 ,CP_UPPER  ,CP_UPPER  ,
    CP_LOWER  ,CP_LOWER  ,CP_LOWER  ,CP_MIDDLE ,CP_UPPER  ,CP_UPPER  ,CP_UPPER  ,CP_MIDDLE ,
	CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_UPPER  ,
    CP_UPPEST ,CP_UPPEST ,CP_UPPEST ,CP_UPPEST ,CP_UPPEST ,CP_UPPER  ,CP_UPPER  ,CP_MIDDLE ,
	CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,
	CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE ,CP_MIDDLE
};
