/****************************************************************************/
/*  KBDCODE.H 15 JAN 89                                                     */
/*  Updated: Suttipong Kanakakorn                                           */
/*           Sun  08-06-1989  13:24:38                                      */
/****************************************************************************/
/**********************************/
/*    key code constant   6/11/87 */
/**********************************/

#define    ESCKEY       0x0011B
#define    RETKEY       0x01C0D
#define    BSKEY        0x00E08
#define    TABKEY       0x00F09
#define    CNTRLRET     0x01C0A
#define    CNTRLBS      0x00E7F
#define    SHFTTAB      0x00F00

/**********************************/
/*    control key constant        */
/**********************************/
#define    CNTRL_A      0x01E01
#define    CNTRL_B      0x03002
#define    CNTRL_C      0x02E03
#define    CNTRL_D      0x02004
#define    CNTRL_E      0x01205
#define    CNTRL_F      0x02106
#define    CNTRL_G      0x02207
#define    CNTRL_H      0x02308
#define    CNTRL_I      0x01709
#define    CNTRL_J      0x0240A
#define    CNTRL_K      0x0250B
#define    CNTRL_L      0x0260C
#define    CNTRL_M      0x0320D
#define    CNTRL_N      0x0310E
#define    CNTRL_O      0x0180F
#define    CNTRL_P      0x01910
#define    CNTRL_Q      0x01011
#define    CNTRL_R      0x01312
#define    CNTRL_S      0x01F13
#define    CNTRL_T      0x01414
#define    CNTRL_U      0x01615
#define    CNTRL_V      0x02F16
#define    CNTRL_W      0x01117
#define    CNTRL_X      0x02D18
#define    CNTRL_Y      0x01519
#define    CNTRL_Z      0x02C1A
#define    CNTRLESC     0x01A1B
#define    CNTRLFS      0x02B1C
#define    CNTRLGS      0x01B1D
#define    CNTRLRS      0x0071E
#define    CNTRLUS      0x00C1F

/**********************************/
/*     alternate code constant    */
/**********************************/
#define    ALT1         0x07800
#define    ALT2         0x07900
#define    ALT3         0x07A00
#define    ALT4         0x07B00
#define    ALT5         0x07C00
#define    ALT6         0x07D00
#define    ALT7         0x07E00
#define    ALT8         0x07F00
#define    ALT9         0x08000
#define    ALT0         0x08100
#define    ALTA         0x01E00
#define    ALTB         0x03000
#define    ALTC         0x02E00
#define    ALTD         0x02000
#define    ALTE         0x01200
#define    ALTF         0x02100
#define    ALTG         0x02200
#define    ALTH         0x02300
#define    ALTI         0x01700
#define    ALTJ         0x02400
#define    ALTK         0x02500
#define    ALTL         0x02600
#define    ALTM         0x03200
#define    ALTN         0x03100
#define    ALTO         0x01800
#define    ALTP         0x01900
#define    ALTQ         0x01000
#define    ALTR         0x01300
#define    ALTS         0x01F00
#define    ALTT         0x01400
#define    ALTU         0x01600
#define    ALTV         0x02F00
#define    ALTW         0x01100
#define    ALTX         0x02D00
#define    ALTY         0x01500
#define    ALTZ         0x02C00

/**********************************/
/*    Direction key constant      */
/**********************************/
#define    HOMEKEY      0x04700
#define    CHOMEKEY     0x07700
#define    UPKEY        0x04800
#define    PGUPKEY      0x04900
#define    CPGUPKEY     0x08400
#define    LEKEY        0x04B00
#define    CLEKEY       0x07300
#define    RIKEY        0x04D00
#define    CRIKEY       0x07400
#define    ENDKEY       0x04F00
#define    CENDKEY      0x07500
#define    DNKEY        0x05000
#define    PGDNKEY      0x05100
#define    CPGDNKEY     0x07600
#define    INSKEY       0x05200
#define    DELKEY       0x05300

/**********************************/
/*     Numeric key constant       */
/*    By Suttipong Kanakakorn     */
/*   Sun  08-06-1989  13:26:33    */
/*   NP = numeric keypad          */
/**********************************/
#define    SHIFT_GRAY_SLASH   0x352F
#define    SHIFT_GRAY_PLUS    0x4E2B
#define    SHIFT_GRAY_MINUS   0x4A2D
#define    GRAY_SLASH   0x352F
#define    GRAY_STAR    0x372A
#define    GRAY_MINUS   0x4A2D
#define    GRAY_PLUS    0x4E2B
#define    SHIFT_1_NP   0x4F31
#define    SHIFT_2_NP   0x5032
#define    SHIFT_3_NP   0x5133
#define    SHIFT_4_NP   0x4B34
#define    SHIFT_5_NP   0x4C35
#define    SHIFT_6_NP   0x4D36
#define    SHIFT_7_NP   0x4737
#define    SHIFT_8_NP   0x4838
#define    SHIFT_9_NP   0x4939
#define    SHIFT_0_NP   0x5230
#define    SHIFT_DOT_NP 0x532E


/**********************************/
/*    function key constant       */
/**********************************/
#define    F1KEY        0x03B00
#define    F2KEY        0x03C00
#define    F3KEY        0x03D00
#define    F4KEY        0x03E00
#define    F5KEY        0x03F00
#define    F6KEY        0x04000
#define    F7KEY        0x04100
#define    F8KEY        0x04200
#define    F9KEY        0x04300
#define    F10KEY       0x04400
#define    UF1KEY       0x05400
#define    UF2KEY       0x05500
#define    UF3KEY       0x05600
#define    UF4KEY       0x05700
#define    UF5KEY       0x05800
#define    UF6KEY       0x05900
#define    UF7KEY       0x05A00
#define    UF8KEY       0x05B00
#define    UF9KEY       0x05C00
#define    UF10KEY      0x05D00

#define    CF1KEY       0x05E00
#define    CF2KEY       0x05F00
#define    CF3KEY       0x06000
#define    CF4KEY       0x06100
#define    CF5KEY       0x06200
#define    CF6KEY       0x06300
#define    CF7KEY       0x06400
#define    CF8KEY       0x06500
#define    CF9KEY       0x06600
#define    CF10KEY      0x06700
#define    AF1KEY       0x06800
#define    AF2KEY       0x06900
#define    AF3KEY       0x06A00
#define    AF4KEY       0x06B00
#define    AF5KEY       0x06C00
#define    AF6KEY       0x06D00
#define    AF7KEY       0x06E00
#define    AF8KEY       0x06F00
#define    AF9KEY       0x07000
#define    AF10KEY      0x07100
